// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * RawMessage is a raw encoded JSON value.
 * It implements [Marshaler] and [Unmarshaler] and can
 * be used to delay JSON decoding or precompute a JSON encoding.
 * @typedef {$models.RawMessage} RawMessage
 */
