// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * ApplyResult 描述一次配置写入/重启的结果。
 */
export class ApplyResult {
    /**
     * Creates a new ApplyResult instance.
     * @param {Partial<ApplyResult>} [$$source = {}] - The source object to create the ApplyResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.APIError | null | undefined}
             */
            this["api_error"] = undefined;
        }
        if (!("rolled_back" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rolled_back"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplyResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("api_error" in $$parsedSource) {
            $$parsedSource["api_error"] = $$createField1_0($$parsedSource["api_error"]);
        }
        return new ApplyResult(/** @type {Partial<ApplyResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = model$0.APIError.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
