// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoxdAuthService 暴露登录（远程模式用）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AutoLogin 内嵌模式自动登录：基于存储的 JWT 密钥签发短期 token，免手动登录。
 * 返回 AuthResponse 供前端注入会话。
 * @returns {$CancellablePromise<any>}
 */
export function AutoLogin() {
    return $Call.ByID(539708412);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Mode() {
    return $Call.ByID(51980611);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RemoteURL() {
    return $Call.ByID(794686263);
}
