// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoxdBridgeService 提供 REST 风格路径到用例层的通用分发，供前端 transport 复用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Call 按路径分派到对应用例方法。返回统一信封，前端无需感知 bindings 细节。
 * @param {$models.BridgeRequest} req
 * @returns {$CancellablePromise<$models.BridgeResponse>}
 */
export function Call(req) {
    return $Call.ByID(683124523, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BridgeResponse.createFrom;
