// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoxdStatsService 暴露流量/连接。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<any>}
 */
export function Connections() {
    return $Call.ByID(2031690724);
}

/**
 * @returns {$CancellablePromise<any>}
 */
export function Traffic() {
    return $Call.ByID(2466723492);
}
