// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoxdSettingsService 暴露应用设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<any>}
 */
export function GetUIPreferences() {
    return $Call.ByID(763626703);
}

/**
 * @param {{ [_ in string]?: any }} prefs
 * @returns {$CancellablePromise<any>}
 */
export function SetUIPreferences(prefs) {
    return $Call.ByID(694232147, prefs);
}
