// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoxdConfigService 暴露配置相关用例逻辑给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../internal/service/models.js";

/**
 * @returns {$CancellablePromise<any>}
 */
export function Get() {
    return $Call.ByID(1719956020);
}

/**
 * @param {string} body
 * @returns {$CancellablePromise<service$0.ApplyResult>}
 */
export function Update(body) {
    return $Call.ByID(1373116041, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} body
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function Validate(body, source) {
    return $Call.ByID(3074635262, body, source);
}

// Private type creation functions
const $$createType0 = service$0.ApplyResult.createFrom;
