// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService 提供原生文件对话框能力（打开/保存文件）。
 * 通过 Wails Dialog 管理器实现，GTK4 走 xdg-desktop-portal。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenConfig 打开文件选择器选取 sing-box 配置文件。
 * @returns {$CancellablePromise<string>}
 */
export function OpenConfig() {
    return $Call.ByID(3720717899);
}

/**
 * OpenJSON 打开文件选择器选取任意 JSON 文件（导入用）。
 * @returns {$CancellablePromise<string>}
 */
export function OpenJSON() {
    return $Call.ByID(3562200007);
}

/**
 * SaveBackup 打开保存对话框导出备份归档。
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveBackup(filename) {
    return $Call.ByID(923465046, filename);
}

/**
 * SaveJSON 打开保存对话框导出 JSON 文件。
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function SaveJSON(filename) {
    return $Call.ByID(2516163802, filename);
}
