// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

/**
 * BridgeRequest 描述一次传输无关的用例调用。
 */
export class BridgeRequest {
    /**
     * Creates a new BridgeRequest instance.
     * @param {Partial<BridgeRequest>} [$$source = {}] - The source object to create the BridgeRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["body"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BridgeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BridgeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BridgeRequest(/** @type {Partial<BridgeRequest>} */($$parsedSource));
    }
}

/**
 * BridgeResponse 描述用例调用结果。
 */
export class BridgeResponse {
    /**
     * Creates a new BridgeResponse instance.
     * @param {Partial<BridgeResponse>} [$$source = {}] - The source object to create the BridgeResponse.
     */
    constructor($$source = {}) {
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["data"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BridgeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BridgeResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BridgeResponse(/** @type {Partial<BridgeResponse>} */($$parsedSource));
    }
}
