// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NativeCapabilities 提供桌面原生能力：自启、单实例、对话框、通知、数据目录等。
 * 封装为 Wails 可绑定服务，供前端与托盘调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ConfigPath 返回内嵌模式配置文件路径。
 * @returns {$CancellablePromise<string>}
 */
export function ConfigPath() {
    return $Call.ByID(3344001682);
}

/**
 * DataDir 返回内嵌模式数据目录。
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByID(295689410);
}

/**
 * IsAutostartEnabled 返回开机自启是否已启用。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAutostartEnabled() {
    return $Call.ByID(3800831361);
}

/**
 * Notify 发送系统通知（Linux 通过 freedesktop 通知规范，不依赖 notify-send）。
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function Notify(title, message) {
    return $Call.ByID(2375499478, title, message);
}

/**
 * ResolvePath 解析相对路径为绝对路径（供文件对话框使用）。
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ResolvePath(path) {
    return $Call.ByID(1336205862, path);
}

/**
 * Runtime 返回桌面运行时信息。
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function Runtime() {
    return $Call.ByID(1835281693).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetAutostart 启用/禁用开机自启。
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutostart(enabled) {
    return $Call.ByID(2030416698, enabled);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
